/zoom/cv_camera_zoom:
  ros__parameters:
    port: 3-4.4.2:1.0
    name: "zoom"
    publish_rate: 10.0
    read_rate: 30.0
    flip: 0
    width: 640.0
    height: 360.0
    fourcc: 1196444237.0
    topic_name: /video_mapping/zoom
    cam_info_topic: None
    topic_sim: "/gazebo/streaming_cam_zoom/image_raw"
    cam_info_period: 5  
    intrinsic: True
    type: USB
    video_path: None
    object_detection: False
    semantic_segmentation: False
    qr_scan: False
    data_capture_csv: True
    data_capture_video: False
    # device_id: 0
    # file_path: ''
    # frame_id: camera
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: best_effort
    use_sim_time: False

/left/cv_camera_left:
  ros__parameters:
    port: 3-4.4.4:1.0
    name: "left"
    publish_rate: 10.0
    read_rate: 30.0
    flip: 0
    width: 640.0
    height: 360.0
    fourcc: 1196444237.0
    topic_name: /video_mapping/left
    cam_info_topic: None
    topic_sim: "/gazebo/streaming_cam_left/image_raw"
    cam_info_period: 5  
    intrinsic: True
    type: USB
    video_path: None
    object_detection: False
    semantic_segmentation: False
    qr_scan: False
    data_capture_csv: True
    data_capture_video: False
    # device_id: 0
    # file_path: ''
    # frame_id: camera
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: best_effort
    use_sim_time: False

/right/cv_camera_right:
  ros__parameters:
    port: 3-4.4.1:1.0
    name: "right"
    publish_rate: 10.0
    read_rate: 30.0
    flip: 0
    width: 640.0
    height: 360.0
    fourcc: 1196444237.0
    topic_name: /video_mapping/right
    cam_info_topic: None
    topic_sim: "/gazebo/streaming_cam_right/image_raw"
    cam_info_period: 5  
    intrinsic: True
    type: USB
    video_path: None
    object_detection: False
    semantic_segmentation: False
    qr_scan: False
    data_capture_csv: True
    data_capture_video: False
    # device_id: 0
    # file_path: ''
    # frame_id: camera
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: best_effort
    use_sim_time: False

/back/cv_camera_back:
  ros__parameters:
    port: 3-4.4.3:1.0
    name: "back"
    publish_rate: 10.0
    read_rate: 30.0
    flip: 0
    width: 640.0
    height: 360.0
    fourcc: 1196444237.0
    topic_name: /video_mapping/back
    cam_info_topic: None
    topic_sim: "/gazebo/streaming_cam_back/image_raw"
    cam_info_period: 5  
    intrinsic: True
    type: USB
    video_path: None
    object_detection: False
    semantic_segmentation: False
    qr_scan: False
    data_capture_csv: True
    data_capture_video: False
    # device_id: 0
    # file_path: ''
    # frame_id: camera
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: best_effort
    use_sim_time: False

